services:
  h2:
    image: oscarfonts/h2
    ports:
      - '8081:8081'
      - '1521:1521'
    environment:
      - H2_USER=T7_OFFLINE_BOT_DB_USERNAME
      - H2_PASS=T7_OFFLINE_BOT_DB_PASSWORD
    volumes:
      - ./db.mv.db:/opt/h2-data/db.mv.db
    restart: always
    networks:
      - host-network

  tekken7-offline-tg-bot:
    image: tekken7-offline-tg-bot:latest
    ports:
      - '8080:8080'
    env_file: ./.env
    networks:
      - host-network

networks:
  host-network:
    driver: bridge
