services:
  h2:
    image: oscarfonts/h2
    ports:
      - "8081:8081"
      - "1521:1521"
    environment:
      - H2_USER=T7_OFFLINE_BOT_DB_USERNAME
      - H2_PASS=T7_OFFLINE_BOT_DB_PASSWORD
    volumes:
      - ./db.mv.db:/opt/h2-data/db.mv.db
    restart: always
    networks:
      - host-network

  tekken7-offline-tg-bot:
    image: tekken7-offline-tg-bot:latest
    environment:
      - T7_OFFLINE_BOT_DB_PASSWORD
      - T7_OFFLINE_BOT_DB_USERNAME
      - T7_OFFLINE_BOT_TOKEN
      - T7_OFFLINE_BOT_USERNAME
      - VIRUS_TOTAL_API_KEY
    networks:
      - host-network

networks:
  host-network:
    driver: bridge
    name: host-network
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
