version: '3.7'

services:
  h2:
    image: oscarfonts/h2
    network_mode: host
    environment:
      - H2_USER=T7_OFFLINE_BOT_DB_USERNAME
      - H2_PASS=T7_OFFLINE_BOT_DB_PASSWORD
    volumes:
      - /home/gzelante/db.mv.db:/data/h2  # Mount the database file to the H2 container
    restart: always

  tekken7-offline-tg-bot:
    image: tekken7-offline-tg-bot:latest
    network_mode: host
    environment:
      - T7_OFFLINE_BOT_DB_PASSWORD
      - T7_OFFLINE_BOT_DB_USERNAME
      - T7_OFFLINE_BOT_TOKEN
      - T7_OFFLINE_BOT_USERNAME
      - VIRUS_TOTAL_API_KEY
    restart: always