   name: Create Branch on Issue

   on:
     issues:
       types: [opened]

   jobs:
     create-branch:
       runs-on: ubuntu-latest
       steps:
         - name: Checkout repository
           uses: actions/checkout@v2

         - name: Determine branch type
           id: branch_type
           run: |
             if [[ "${{ github.event.issue.labels }}" == *"feature"* ]]; then
               echo "type=feature" >> $GITHUB_ENV
             elif [[ "${{ github.event.issue.labels }}" == *"release"* ]]; then
               echo "type=release" >> $GITHUB_ENV
             elif [[ "${{ github.event.issue.labels }}" == *"hotfix"* ]]; then
               echo "type=hotfix" >> $GITHUB_ENV
             else
               echo "type=other" >> $GITHUB_ENV
             fi

         - name: Create branch
           if: env.type != 'other'
           env:
             ISSUE_NUMBER: ${{ github.event.issue.number }}
             ISSUE_TITLE: ${{ github.event.issue.title }}
             BRANCH_TYPE: ${{ env.type }}
           run: |
             BRANCH_NAME="${BRANCH_TYPE}/issue-${ISSUE_NUMBER}-${ISSUE_TITLE// /-}"
             git config --global user.name "github-actions[bot]"
             git config --global user.email "github-actions[bot]@users.noreply.github.com"
             git checkout -b "$BRANCH_NAME"
             git push origin "$BRANCH_NAME"
