   name: Create Branch on Issue

   on:
     issues:
       types: [opened]
   
   jobs:
     create-branch:
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v4.2.2
         - uses: actions/setup-node@v4.1.0
         - name: Create Branch
           uses: actions/github-script@v7.0.1
           with:
             script: |
               const core = require('@actions/core');
               const github = require('@actions/github');
   
               async function run() {
                 try {
                   const issue = github.context.issue;
                   const issueNumber = issue.number;
                   const issueTitle = issue.title;
   
                   // Sanitize the issue title for branch name
                   const sanitizedTitle = issueTitle.replace(/[^a-zA-Z0-9 ]/g, '').replace(/\s+/g, '-').toLowerCase();
   
                   const branchName = `feature/${issueNumber}-${sanitizedTitle}`;
   
                   // Create the branch
                   await github.rest.git.createRef({
                     owner: context.repo.owner,
                     repo: context.repo.repo,
                     ref: `refs/heads/${branchName}`,
                     sha: context.sha   
   
                   });
   
                   core.setOutput('branch-name', branchName);
                 } catch (error) {
                   core.setFailed(error.message);
                 }
               }
   
               run();
