   name: Create Branch on Issue

   on:
     issues:
       types:
         - assigned
    
   jobs:
     create_issue_branch_job:
       runs-on: ubuntu-latest
       steps:
         - name: Check out repository
           uses: actions/checkout@v4.2.2
         - name: Create issue branch
           run: |
              git config user.name 'github-actions'
              git config user.email '41898282+github-actions[bot]@users.noreply.github.com'   
      
              title=${title// /-}
              branchname=feature/$number-${title,,}
              git switch -c "$branchname"
              git push -u origin "$branchname"
