name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build and clean Docker image
        run: ./gradlew clean optimizedDockerBuild --info --stacktrace

      - name: List Docker images
        run: docker images

      - name: Get Docker image ID
        id: get_image_id
        run: echo "IMAGE_ID=$(docker images -q | head -n 1)" >> $GITHUB_OUTPUT

      - name: Save Docker image to tar file
        run: docker save ${{ steps.get_image_id.outputs.IMAGE_ID }} > tekken7-offline-tg-bot.tar

      - name: SSH into remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USERNAME }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          port: ${{ secrets.REMOTE_PORT }}
          script: |
            docker kill t7_offline_tg_bot
            docker load -i /home/gzelante/tekken7-offline-tg-bot.tar
            docker run -d -e T7_OFFLINE_BOT_DB_PASSWORD \
                          -e T7_OFFLINE_BOT_DB_USERNAME \
                          -e T7_OFFLINE_BOT_TOKEN \
                          -e T7_OFFLINE_BOT_USERNAME \
                          -e VIRUS_TOTAL_API_KEY \
                          --rm --name t7_offline_tg_bot -it tekken7-offline-tg-bot:latest
