name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-disabled: true
      - name: Build Docker image
        run: ./gradlew build optimizedDockerBuild
      - name: List directories
        run: ls -latr
      - name: Save Docker image to tar file
        run: docker save tekken7-offline-tg-bot:latest > tekken7-offline-tg-bot.tar
      - name: Transfer tar file to remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USERNAME }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          port: ${{ secrets.REMOTE_PORT }}
          script: |
            scp -P ${{ secrets.REMOTE_PORT }} tekken7-offline-tg-bot.tar ${{ secrets.REMOTE_USERNAME }}@${{ secrets.REMOTE_HOST }}:/home/gzelante
      - name: SSH into remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USERNAME }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          port: ${{ secrets.REMOTE_PORT }}
          script: |
            ssh -p ${{ secrets.REMOTE_PORT }} ${{ secrets.REMOTE_USERNAME }}@${{ secrets.REMOTE_HOST }} 'cd /home/gzelante && docker stop t7_offline_tg_bot && docker load -i tekken7-offline-tg-bot.tar && docker run -d -e T7_OFFLINE_BOT_DB_PASSWORD -e T7_OFFLINE_BOT_DB_USERNAME -e T7_OFFLINE_BOT_TOKEN -e T7_OFFLINE_BOT_USERNAME -e VIRUS_TOTAL_API_KEY --rm --name t7_offline_tg_bot -it tekken7-offline-tg-bot:latest'
