name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-disabled: false
          cache-read-only: true
          cache-write-only: false
          cache-overwrite-existing: false
          gradle-home-cache-includes: caches
      - name: Build Docker image
        run: ./gradlew build optimizedDockerBuild
      - name: List directories
        run: tree
